---
- name: odoo install mods and apps
  become: yes
  become_user: "{{ user }}"
  loop: "{{ mods }}"
  command: "{{ home }}/odoo-bin -c /etc/odoo/odoo.conf --no-http --stop-after-init --without-demo=all -i {{ item }}"
