---
- name: create {{ user }} group
  group:
    name: "{{ user }}"
    gid: 114
    state: present
- name: create {{ user }} user
  user:
    name: "{{ user }}"
    uid: 107
    groups:
      - "{{ user }}"
      - sudo
    home: "{{ home }}"
    shell: /bin/bash
    state: present
- name: change ownership
  file:
    path: "{{ home }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes
