---
- name: Converge
  hosts: all
  vars:
    home: "/var/lib/odoo"
    config: "/var/lib/odoo/.config"
    local: "/var/lib/odoo/.local"
    user: "odoo"
  tasks:
    - name: update cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    - name: odoo_mod_install
      include_role:
        name: odoo_mod_install
