---
- name: smbd
  systemd:
    name: smbd
    state: stopped
    enabled: no
    masked: yes
- name: nmbd
  systemd:
    name: nmbd
    state: stopped
    enabled: no
    masked: yes
- name: winbind
  systemd:
    name: winbind
    state: stopped
    enabled: no
    masked: yes
- name: samba-ad-dc
  systemd:
    name: samba-ad-dc
    enabled: yes
    masked: no
