---
- name: update
  apt:
    update_cache: yes
    force_apt_get: yes

- name: network tools
  apt:
    name:
      - nmap
    state: present

- name: cli helpers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - { src: "nscan", dest: "{{ home }}/bin/", mode: "0755" }
