---
- name: apt mirror - debian
  template:
    src: "sources.debian.list"
    dest: "/etc/apt/sources.list"
    mode: "0644"
  when: ansible_distribution == 'Debian'
- name: apt mirror - ubuntu
  template:
    src: "sources.ubuntu.list"
    dest: "/etc/apt/sources.list"
    mode: "0644"
  when: ansible_distribution == 'Ubuntu'
- name: cache update
  apt:
    update_cache: yes
