---
- name: sshd PasswordAuthentication yes
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication.*$'
    replace: 'PasswordAuthentication yes'
- name: restart ssh
  systemd:
    name: ssh
    enabled: yes
    daemon_reload: yes
    state: restarted

