---
- name: update
  apt:
    update_cache: yes
    force_apt_get: yes

- name: remote file systems
  apt:
    name:
      - rsync
      - curlftpfs
      - sshfs
      - nfs-common
      - samba
      - cifs-utils
      - krb5-user
    state: present
