---
# syncthing
- name: syncthing repo key
  apt_key:
    url: "https://syncthing.net/release-key.txt"
    state: present
- name: syncthing repository stat
  stat:
    path: "/etc/apt/sources.list.d/syncthing.list"
  register: stat_result
- name: syncthing repository remove
  file:
    path: "/etc/apt/sources.list.d/syncthing.list"
    state: absent
  when: stat_result.stat.exists
- name: syncthing repository add
  apt_repository:
    validate_certs: no
    repo: "deb [arch=amd64] https://apt.syncthing.net/ syncthing stable"
    state: present
    filename: syncthing
    update_cache: yes
- name: syncthing
  apt:
    name:
    - syncthing
    state: latest
