---
- name: sshd PubkeyAuthentication yes
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication.*$'
    replace: 'PubkeyAuthentication yes'
- name: restart ssh
  systemd:
    name: ssh
    enabled: yes
    daemon_reload: yes
    state: restarted

