---
- name: git
  apt:
    name:
      - git
    state: present
- name: hugoup
  template:
    src: "bin/hugoup"
    dest: "{{ home }}/bin/hugoup"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
