---
- name: pgbouncer install
  apt:
    name: pgbouncer
    state: present
- name: pgbouncer config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "root"
    group: "root"
  with_items:
    - { src: "pgbouncer.ini", dest: "/etc/pgbouncer", mode: "0644" }
    - { src: "userlist.txt", dest: "/etc/pgbouncer", mode: "0644" }
- name: pgbouncer restart
  systemd:
    name: pgbouncer
    state: restarted
