---
- name: proxmox-ve repo key
  apt_key:
    url: "http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg"
    state: present
- name: proxmox-ve repo file stat
  stat:
    path: "/etc/apt/sources.list.d/pve-install-repo.list"
- name: proxmox-ve repo file remove
  file:
    path: "/etc/apt/sources.list.d/pve-install-repo.list"
    state: absent
  when: stat_result.stat.exists
- name: proxmox-ve repo
  apt_repository:
    validate_certs: no
    repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve buster pve-no-subscription"
    state: present
    filename: pve-install-repo
    update_cache: yes
- name: proxmox-ve
  apt:
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
    state: present
- name: remove os-prober
  apt:
    name:
      - os-prober
    state: absent
