---
- name: zoneminder repo key
  apt_key:
    url: "https://zmrepo.zoneminder.com/debian/archive-keyring.gpg"
    state: present
- name: zoneminder repository stat
  stat:
    path: "/etc/apt/sources.list.d/zoneminder.list"
  register: stat_result
- name: zoneminder repository remove
  file:
    path: "/etc/apt/sources.list.d/zoneminder.list"
    state: absent
  when: stat_result.stat.exists
- name: zoneminder repo {{ ansible_lsb.codename|lower }}
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://zmrepo.zoneminder.com/debian/release {{ ansible_lsb.codename|lower }}/
    state: present
    filename: zoneminder
    update_cache: yes
