---
- name: update
  apt:
    update_cache: yes
    force_apt_get: yes

- name: fs utils
  apt:
    name:
      - e2fsprogs
      - xfsprogs
      - btrfs-progs
      - zfsutils-linux
      - ntfs-3g
    state: latest
