---
- name: update
  apt:
    update_cache: yes
    force_apt_get: yes

- import_role:
    name: baseline
# base utils
- name: downloaders
  apt:
    name:
      - aria2
      - netcat
      - pv
    state: present
- name: file utils
  apt:
    name:
      - gddrescue
    state: present
- name: compression
  apt:
    name:
      - lzop
      - pigz
        #- unrar
      - cabextract
      - upx-ucl
    state: present
- name: unrar ubuntu
  apt:
    name:
      - unrar
    state: present
  when: ansible_distribution == "Ubuntu"
- name: unrar debian
  apt:
    name:
      - unrar-free
    state: present
  when: ansible_distribution == "Debian"
- name: mail utils
  apt:
    name:
      - swaks
    state: present
- name: monitoring
  apt:
    name:
      - htop
      - nmon
      - tmux
      - screenfetch
    state: present
