---
- import_role:
    name: baseline
- name: nodejs gpg key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
- name: nodejs repository
  vars:
    alc: "{{ ansible_lsb.codename|lower }}"
    nv: "{{ NODE_VERSION }}"
    ruri: "https://deb.nodesource.com/node_"
  apt_repository:
    validate_certs: no
    repo: "deb [arch=amd64] {{ ruri }}{{ nv }}.x {{ alc }} main"
    state: present
    filename: nodesource
    update_cache: yes
- name: nodejs install
  apt:
    name:
      - nodejs
    state: present
