---
- name: update
  apt:
    update_cache: yes
    force_apt_get: yes

# javascript
- name: nodejs gpg key
  apt_key:
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    state: present
- name: nodejs repository remove
  apt_repository:
    validate_certs: no
    repo: 'deb [arch=amd64] https://deb.nodesource.com/node_{{NODE_VERSION}}.x {{ ansible_lsb.codename|lower }} main'
    state: absent
    filename: nodesource
- name: nodejs repository
  apt_repository:
    validate_certs: no
    repo: 'deb [arch=amd64] https://deb.nodesource.com/node_{{NODE_VERSION}}.x {{ ansible_lsb.codename|lower }} main'
    state: present
    filename: nodesource
    update_cache: yes
- name: nodejs install
  apt:
    name:
      - nodejs
    state: present
