---
- name: addons directory
  file:
    path: /opt/addons
    state: directory
    group: "{{ user }}"
    owner: "{{ user }}"
- name: config directory
  file:
    path: /etc/odoo
    state: directory
    group: "{{ user }}"
    owner: "{{ user }}"
- name: copy odoo config
  template:
    src: odoo.conf
    dest: /etc/odoo/odoo.conf
