---
- import_role:
    name: odoo_user
- name: addons directory
  file:
    path: /opt/addons
    state: directory
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775
- name: enterprise addons directory
  file:
    path: /opt/enterprise
    state: directory
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775
- name: config directory
  file:
    path: /etc/odoo
    state: directory
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775
- name: copy odoo config
  template:
    src: odoo.conf
    dest: /etc/odoo/odoo.conf
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0664
