---
- import_role:
    name: lang_ruby
- import_role:
    name: lang_ruby_config
- import_role:
    name: lang_java
- name: graphviz
  apt:
    name:
      - graphviz
    state: present
- name: asciidoctor-pdf
  become_user: "{{ user }}"
  gem:
    name: asciidoctor-pdf
    state: latest
    pre_release: yes
    user_install: yes
- name: asciidoctor
  become_user: "{{ user }}"
  gem:
    name: asciidoctor
    state: latest
    #user_install: yes
- name: asciidoctor-diagram
  become_user: "{{ user }}"
  gem:
    name: asciidoctor-diagram
    state: latest
    #user_install: yes
- name: asciidoctor-rouge
  become_user: "{{ user }}"
  gem:
    name: asciidoctor-rouge
    state: latest
    #user_install: yes
- name: rouge
  become_user: "{{ user }}"
  gem:
    name: rouge
    state: latest
    #user_install: yes
- name: coc snippets asciidoc
  template:
    src: "coc/ultisnips/asciidoc.snippets"
    dest: "{{ config }}/coc/ultisnips/"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
- name: asciidoctor helpers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - { src: "bin/adoc2pdf", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/adoc2pdfwatch", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/asciidocup", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/talk2pdf", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/talksched2pdf", dest: "{{ home }}/bin/", mode: "0755" }
