---
- name: graphviz
  apt:
    name:
      - graphviz
    state: present
- name: asciidoctor-pdf
  become_user: "{{ user }}"
  gem:
    name: asciidoctor-pdf
    state: latest
    pre_release: yes
    user_install: yes
- name: asciidoctor-diagram
  become_user: "{{ user }}"
  gem:
    name: asciidoctor-diagram
    state: latest
    #user_install: yes
- name: asciidoctor-html5s
  become_user: "{{ user }}"
  gem:
    name: asciidoctor-html5s
    state: latest
    #user_install: yes
- name: asciidoctor-rouge
  become_user: "{{ user }}"
  gem:
    name: asciidoctor-rouge
    state: latest
    #user_install: yes
- name: rouge
  become_user: "{{ user }}"
  gem:
    name: rouge
    state: latest
    #user_install: yes
- name: asciidoctor
  become_user: "{{ user }}"
  gem:
    name: asciidoctor
    state: latest
    #user_install: yes
- name: coc snippets asciidoc
  template:
    src: "coc/ultisnips/asciidoc.snippets"
    dest: "{{ config }}/coc/ultisnips/"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
- name: asciidoctor helpers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - { src: "bin/adoc2pdf", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/adoc2pdfwatch", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/asciidocup", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/nerdfonts", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/talk2pdf", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/talksched2pdf", dest: "{{ home }}/bin/", mode: "0755" }
- name: install fonts
  command: "{{ home }}/bin/nerdfonts"
  become_user: "{{ user }}"
- name: pdf fonts
  get_url:
    url: "{{ item.src }}"
    dest: "{{ home }}/.fonts"
    mode: 0640
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/mplus1mn-bold-subset.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/mplus1mn-bold_italic-subset.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/mplus1mn-italic-subset.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/mplus1mn-regular-subset.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/mplus1p-regular-fallback.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/notoserif-bold-subset.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/notoserif-bold_italic-subset.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/notoserif-italic-subset.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/notoserif-regular-subset.ttf",
      }
    - {
        src: "https://github.com/asciidoctor/asciidoctor-pdf/raw/master/data/fonts/notoemoji-subset.ttf",
      }
- name: config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - {
        src: "config/themes/basic-theme.yml",
        dest: "{{ local }}/asciidoc/themes/",
        mode: "0640",
      }
    - {
        src: "config/themes/policy-theme.yml",
        dest: "{{ local }}/asciidoc/themes/",
        mode: "0640",
      }
    - {
        src: "config/themes/talk-theme.yml",
        dest: "{{ local }}/asciidoc/themes/",
        mode: "0640",
      }
