---
- name: install snapd
  apt:
    name:
      - snapd
      - squashfuse
    state: present
    update_cache: yes
- name: install microk8s
  snap:
    name: microk8s
    state: present
    classic: yes
