---
- import_role:
    name: baseline
- name: repo key
  apt_key:
    url: "{{url}}/x{{distro}}/Release.key"
    state: present
  when: ansible_distribution == "Ubuntu"
- name: repo key
  apt_key:
    url: "{{url}}/{{distro}}/Release.key"
    state: present
  when: ansible_distribution == "Debian"
- name: repository add
  apt_repository:
    validate_certs: no
    repo: "deb {{url}}/x{{distro}}/ /"
    filename: podman
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
- name: repository add
  apt_repository:
    validate_certs: no
    repo: "deb {{url}}/{{distro}}/ /"
    filename: podman
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"
