---
- name: odoo.service file
  template:
    src: "odoo.service"
    dest: "/lib/systemd/system/"
    mode: "0644"
- name: enable odoo.service
  ignore_errors: yes
  systemd:
    name: odoo
    enabled: yes
    daemon_reload: yes
    status: started

